// <auto-generated />
namespace WingStudio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig28 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig28));
        
        string IMigrationMetadata.Id
        {
            get { return "201610091138263_mig28"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
